normal-color = "#4c4f69"
normal-fill-alpha = 0.03
normal-border = "#8c91b5"
normal-border-width = 1
normal-border-alpha = 1.0
hover-cursor-color = "#7d27e1"
hover-cursor-fill-alpha = 0.06
hover-cursor-border = "#7d27e1"
hover-cursor-border-width = 1
hover-cursor-border-alpha = 1.0
focus-color = "#7d27e1"
focus-fill-alpha = 0.06
focus-border = "#7d27e1"
focus-border-width = 2
focus-border-alpha = 1.0
selected-color = "#7d27e1"
selected-fill-alpha = 0.08
selected-border = "#7d27e1"
selected-border-width = 1
selected-border-alpha = 1.0
pressed-fill-alpha = 0.1
selection-fill-alpha = 0.1
